export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL";

export const COMMENT_DELETE = "COMMENT_DELETE";
export const COMMENT_PUT = "COMMENT_PUT";
export const COMMENT_POST = "COMMENT_POST";

export const COMMENT_DELETE_FAIL = "COMMENT_DELETE_FAIL";
export const COMMENT_PUT_FAIL = "COMMENT_PUT_FAIL";
export const COMMENT_POST_FAIL = "COMMENT_POST_FAIL";

export const COMMENT_REPLY_PUT = "COMMENT_REPLY_PUT";
